### ISSUE TITLE
[question+bug?] icons

### ISSUE THREAD

**Issue by Commandcracker** [flathub/cc.craftos_pc.CraftOS-PC#7]
## icons/hicolor

CraftOS-PC now comes with icons for 16x16 to 1024x1024. The 256x256 icon is currently only used for the flatpacks. IDK if this is intended, but I saw some reverted commits that were icon related. It would still be nice to have high and low resolution icons :)

## Taskbar icons

The Taskbar icon for CraftOS-PC and Accelerated flatpacks are missing on Wayland.
The CraftOS-PC in the top left, where taskbar icons are working, is the [CraftOS-PC rpm](https://github.com/Commandcracker/craftos2-rpm/blob/main/craftos-pc-accelerated.spec)!
The missing Window icons is [another issue](https://github.com/MCJack123/craftos2/issues/320)!

Wayland
![grafik](https://github.com/flathub/cc.craftos_pc.CraftOS-PC/assets/49335821/4af1f299-27a2-4233-8af5-1dce32d6f990)

X11
![grafik](https://github.com/flathub/cc.craftos_pc.CraftOS-PC/assets/49335821/0ec17acc-bb19-44ff-9d6d-b7daba3d121b)

**Comment by ninjawarrior1337** [comment]
I was told to package with only 256x icons by the Flathub maintainers here.
https://github.com/flathub/flathub/pull/3809#discussion_r1073609791
If the smaller icons are used in the application, I would be willing to add them to both packages.

As for the taskbar icons, it seems that KDE has a long issue with windows not showing the correct icon in the taskbar on Wayland.
https://nicolasfella.de/posts/fixing-wayland-taskbar-icons/

My best guess as to why the icon works in the RPM package is that the binary (craftos) shares its name with the icons in the package, which is something that Flatpaks published to Flathub do not allow (the icons and the desktop file must be named with the ID of the Flatpak). Changing the binary name is out of the question as that would require me to patch the upstream desktop and appdata file.

Either way, the link above and https://nicolasfella.de/posts/importance-of-desktop-file-mapping/ both seem to indicate that upstream needs to set the desktop file property on created windows in order for this to work properly in Wayland KDE and would also need agree on a package ID (the name of this repo). Right now, it seems to work correctly by falling back to the correct icon by executable name.

If upstream is unable to resolve this, which from reading the issues sent might be the case, I'll create a wrapper that adds the correct desktop file mapping in an environment variable, although this definitely seems like a last resort solution.

**Comment by Commandcracker** [comment]
> the icons and the desktop file must be named with the ID of the Flatpak

I think this should work, at least it looks like other flatpak's did the same example: [librewolf](https://github.com/flathub/io.gitlab.librewolf-community/blob/master/io.gitlab.librewolf-community.desktop)

**Comment by Commandcracker** [comment]
This var should be helpful [${FLATPAK_ID}](https://github.com/flathub/com.discordapp.Discord/blob/master/com.discordapp.Discord.json#L63) :)

**Comment by Commandcracker** [comment]
> I was told to package with only 256x icons by the Flathub maintainers here.

OK, then it should be better to keep it how it is.
It just looked a bit wired while looking at the commits.

**Comment by ninjawarrior1337** [comment]
"the icons and the desktop file must be named with the ID of the Flatpak" is currently how things work. This same-filename convention is required by Flathub maintainers so that the icon appears on the Flathub website. The application window must communicate this ID to the KDE compositor in order to get icons to work properly.

I'm currently spinning up a Kionite VM in order to run tests and evaluate possible solutions since I personally use GNOME where icons show up perfectly fine.

**Comment by ninjawarrior1337** [comment]
After doing some testing, it turns out that the correct way to fix this is to have upstream call the xdg_toplevel::set_app_id with cc.craftos_pc.CraftOS-PC as the parameter when creating the window.

This will not only fix this issue, but also https://github.com/MCJack123/craftos2/issues/320 as can be seen by this screenshot.
<img width="1512" alt="image" src="https://github.com/flathub/cc.craftos_pc.CraftOS-PC/assets/10366065/12571b2a-f51a-4407-b700-b0e1ceb8abf4">

Unfortunately, this would require upstream to change their app id to align with the Flatpak's as cc.craftos-pc.CraftOS-PC is not a reccomended app id as per the warning [here](https://developer.gnome.org/documentation/tutorials/application-id.html#:~:text=Rules%20for%20application%20IDs&text=the%20application%20ID%20must%20be,not%20start%20with%20a%20digit.) which I could understand why they might not want to.

If having a correct icon is a concern for you, the workaround for apps on KDE can be done by following [this](https://www.reddit.com/r/kde/comments/tzw738/fix_generic_wayland_icon_in_task_manager_for/) and setting the desktop file name property to cc.craftos_pc.CraftOS-PC (the Flatpak's ID) which will fix both the window icon and tray icon.

**Comment by Kontrabant** [comment]
SDL2 has the `SDL_VIDEO_WAYLAND_WMCLASS` envvar, which can be used to override the app ID to match the name of your Flatpak.

**Comment by ninjawarrior1337** [comment]
> SDL2 has the `SDL_VIDEO_WAYLAND_WMCLASS` envvar, which can be used to override the app ID to match the name of your Flatpak.

Can confirm this works and resolves both the titlebar and taskbar icon issues. 

Tracking PR here https://github.com/flathub/cc.craftos_pc.CraftOS-PC/pull/8
